on:
  push:
    branches:
      - main
    paths-ignore:
      - '.github/**'
      - '.vscode/**'
      - 'test/**'
      
name: release-please
jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: google-github-actions/release-please-action@v3
        with:
          release-type: simple
          package-name: release-please-action
          version-file: version.txt
          extra-files: | 
            pubspec.yaml
          changelog-types: |
            [
              { "type": "feat", "section": "Features", "hidden": false },
              { "type": "fix", "section": "Bug Fixes", "hidden": false },
              { "type": "chore", "section": "Miscellaneous", "hidden": false },
              { "type": "refactor","section": "Miscellaneous", "hidden": false },
              { "type": "docs", "section": "Documentation", "hidden": false }
            ]

